### ISSUE TITLE
Patient page surveys should pull from database

### ISSUE THREAD

**Issue by beccannlittle** [ser515asu/PRP-Manhattan-Project#115]

**Comment by ChristianMurphy** [comment]
The code to get survey instance data will be similar to [this](https://github.com/ser515asu/PRP-Manhattan-Project/blob/3595ff0c3f4b6da2617dcf86e0a0b1ea53040fb5/api/handler/get-survey.js#L47)

**Comment by beccannlittle** [comment]
@ChristianMurphy How do you want to handle replying data to the view since the [current code](https://github.com/ser515asu/PRP-Manhattan-Project/blob/survey-view/controller/handler/patient.js#L134) already uses a callback to do this with the patient data? Is there a way to include searching for the surveys at the same time as grabbing the patient, or is a separate callback necessary?

**Comment by ChristianMurphy** [comment]
They can be combined into one call using `Promise.all` like [this](https://github.com/ser515asu/PRP-Manhattan-Project/blob/263981536c43920e7d3a4a519b1e3e6efc20466c/rule/task/create-survey.js#L26)
