### ISSUE TITLE
Charts and DOM manipulation

### ISSUE THREAD

**Issue by beccannlittle** [ser515asu/PRP-Manhattan-Project#19]
We need either server-side DOM manipulation plugin (like [cheerio](https://github.com/cheeriojs/cheerio)) or some sort of server-side chart library

**Comment by ChristianMurphy** [comment]
Why?
Looking at Chart.JS the chart expects [JSON data](http://www.chartjs.org/docs/#radar-chart-data-structure), as long as that gets passed in the chart should work, right?
Am I missing something here?

**Comment by ChristianMurphy** [comment]
There is interest in replacing client side chart.js with server generated svg charts.
Probably from C3.js or D3.js

**Comment by ChristianMurphy** [comment]
Generating the charts server side looks like it would require creating a browser server side and using the server side browser to render the chart.
This seems more complex than running the code on the client.

ref http://www.smashingmagazine.com/2014/05/love-generating-svg-javascript-move-to-server/

**Comment by ChristianMurphy** [comment]
So looking at all the existing solutions rendering the chart server side will be more complex.
There could be a performance increase only if all these conditions are met.

1. The server is more powerful than the client (server needs to do the same work as the client would)
2. Either low number of requests to the server or many servers running (each request will be its own server side browser)
3. Bandwidth for rendered chart is less than bandwidth of un-rendered chart (bandwidth will be limiting for mobile phones and tablets)

Currently 1 is not true, the server is not that fast
and 3 is not true, there isn't really a good way to cache charts that will constantly be changing, and SVG is larger than the JSON data.

**Comment by ChristianMurphy** [comment]
Unless we are given a legacy system support constraint, client rendered chart will be faster and simpler.
Marking this as `won't fix` and closing, we can revisit this later if need be.

**Comment by ChristianMurphy** [comment]
css tricks just wrote an article on SVG charts
https://css-tricks.com/how-to-make-charts-with-svg/
That looks more doable than the rendering charts in server side browser.
