### ISSUE TITLE
Create Trial 'targetCount' attribute

### ISSUE THREAD

**Issue by ChristianMurphy** [ser515asu/PRP-Manhattan-Project#54]
Creating an new Trial is erroring out because it needs a 'targetCount' attribute when creating.
This started after #49 was merged.

**Comment by ChristianMurphy** [comment]
needs validation in the router.
https://github.com/ser515asu/PRP-Manhattan-Project/blob/master/router.js#L22
`targetCount` is type `Joi.number().integer()`

https://github.com/ser515asu/PRP-Manhattan-Project/blob/master/view/partial/add-trial.hbs#L43
Needs a new `<input type="number" name="targetCount">`

**Comment by sylvr3** [comment]
Done!



![0540de8c-7da4-11e5-9f58-5cc30d08ed73](https://cloud.githubusercontent.com/assets/1154846/10808914/01a78bc2-7dae-11e5-8c7f-bce3755d8707.png)

**Comment by beccannlittle** [comment]
Is this supposed to work? It doesn't on my end.
