### ISSUE TITLE
Proper form validation

### ISSUE THREAD

**Issue by beccannlittle** [ser515asu/PRP-Manhattan-Project#57]
For example, [IRB ID](https://docs.google.com/a/asu.edu/document/d/1MZtCh-6quAUBUzdkRMH9XK4KFGvO3M9lzv4xsE7IdT8/edit?usp=sharing)

**Comment by ChristianMurphy** [comment]
What do you mean by 'proper'?
The input is being validated and the appropriate HTTP error code is being returned.

**Comment by beccannlittle** [comment]
UI-side validation

**Comment by ChristianMurphy** [comment]
Got it :+1:
