### ISSUE TITLE
Start Date Terminology and Validation

### ISSUE THREAD

**Issue by beccannlittle** [ser515asu/PRP-Manhattan-Project#71]
- Change "IRB Approval Date" to "Creation Date" (or something like that)
 - UI-side date validation (tooltip)
 - *proper* validation (Today is 11/8 and I couldn't create a trial starting 11/8 or 11/9 for some reason)

**Comment by ChristianMurphy** [comment]
* It still is the approval date, past dates need manual entry
* You can't enter past dates, tooltip would be needed if clinicians *could* enter past dates
* Check that your system time is correct, because those dates can be entered

![capture](https://cloud.githubusercontent.com/assets/3107513/11025312/d9522a22-8656-11e5-9ddd-bd1264473e9a.PNG)

**Comment by beccannlittle** [comment]
"{"statusCode":400,"error":"Bad Request","message":"child \"IRBStart\" fails because [\"IRBStart\" must be larger than or equal to \"Sun Nov 08 2015 20:29:19 GMT-0700 (MST)\"]","validation":{"source":"payload","keys":["IRBStart"]}}"

Looks like the time I'm grabbing is Sun Nov 08 2015 20:29:19 which is correct

**Comment by beccannlittle** [comment]
And you can *manually* enter the wrong date by typing it :)

**Comment by ChristianMurphy** [comment]
400 message on a correct time I will look into.
Manually entering an incorrect date will throw the 400 message. :)

**Comment by beccannlittle** [comment]
Right............. but there should be UI-side validation :)))))

**Comment by ChristianMurphy** [comment]
Resolved the 400 error.
I tested both Chrome and Firefox, an invalid date cannot be entered on those two without DOM manipulation.
Which browser did you test on?

**Comment by beccannlittle** [comment]
Chrome.

**Comment by ChristianMurphy** [comment]
Interesting...
Here's what I get in Chrome.

![capture](https://cloud.githubusercontent.com/assets/3107513/11025638/d17e94d0-865a-11e5-8e62-c4c28416031a.PNG)

**Comment by ChristianMurphy** [comment]
That validation isn't popping up for you?

**Comment by beccannlittle** [comment]
Ah - you have to press Enter. Pressing Tab or clicking out avoids this and other tooltips. 

Also, is there a way to ensure we can't even add a trial until validation passes? The ADD button should probably be disabled

**Comment by ChristianMurphy** [comment]
Pressing 'ADD' should have the same affect as hitting enter, it will show the message and will not attempt to create a trial.
(the above message was triggered when clicking the add button)

**Comment by beccannlittle** [comment]
Ohh, you right you right. So the tooltip is correctly validating date. :white_check_mark:
