### ISSUE TITLE
bodyPain object needs to be empty for all the non-bodyPain questions in the submit_survey API

### ISSUE THREAD

**Issue by poojaRal** [ser515asu/PRP-Manhattan-Project#90]
bodyPain object needs to handled appropriately when it comes as empty for all the non-bodyPain questions.

This needs to be handled in the router.js file

**Comment by ChristianMurphy** [comment]
@poojaRal Router already handles this case, the controller logic may need to be adapted though.

**Comment by poojaRal** [comment]
Yeah.. Looks like that. Need to test it line by line.

**Comment by poojaRal** [comment]
The fix has been identified. 

The validation for allowing empty string in location and intensity are removed.
If the bodyPain object is populated then these values cannot be empty.
This change is done in router.js file

The controller logic for the API is changed to check for bodyPain object value being populated before proceeding with creation of question_instance for bodyPain.
The IF condition for selectedOptions array is modified to check if its not empty before inserting records into question_instance.

These changes have been fixed as part of branch fix_for_issue90.

**Comment by poojaRal** [comment]
Code changes merged to master.
